### ISSUE TITLE
Comment about PWM frequency formula

### ISSUE THREAD

**Issue by koutoftimer** [Rahix/avr-hal#133]
https://github.com/Rahix/avr-hal/blob/master/avr-hal-generic/src/pwm.rs#L9

This is not true. Exact formula can be found in the datasheet for specific board. [atmel328p][datasheet] have several PWM modes on 8 and 16 bit counter. Each mode and counter have it's own formula.

[datasheet]: https://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-7810-Automotive-Microcontrollers-ATmega328P_Datasheet.pdf

**Comment by Rahix** [comment]
It is true for the "Fast PWM" mode which is implemented in this abstraction.  Other modes (#44) will need to be handled separately.
