### ISSUE TITLE
Not generic `impl_pwm`

### ISSUE THREAD

**Issue by koutoftimer** [Rahix/avr-hal#134]
[There](https://github.com/Rahix/avr-hal/blob/master/avr-hal-generic/src/pwm.rs#L106) have to be `Self::Duty::MAX` and ability to define `u16` [here](https://github.com/Rahix/avr-hal/blob/master/avr-hal-generic/src/pwm.rs#L79)

**UPD:** [`get_max_duty()`](https://github.com/Rahix/avr-hal/blob/master/avr-hal-generic/src/pwm.rs#L105) should return TOP value: MAX, OCR or ICR depending on mode (WGM, COM pair).

**Comment by Rahix** [comment]
Let's close this in favor of a new design, like I outlined here: https://github.com/Rahix/avr-hal/issues/130#issuecomment-779072403
