### ISSUE TITLE
Wrong link for atmega328p chip in README

### ISSUE THREAD

**Issue by vmasdani** [Rahix/avr-hal#17]
The link should be in `https://github.com/Rahix/avr-hal/blob/master/chips/atmega328p-hal` but it's pointing to `https://github.com/Rahix/avr-hal/blob/master/'./chips/atmega328p-hal`

**Comment by Rahix** [comment]
Thanks for the hint!  Do you mind creating a quick PR to fix it?

**Comment by vmasdani** [comment]
> Thanks for the hint! Do you mind creating a quick PR to fix it?

I've never made a PR before, I just made a quick fork and created this PR comparing master to my fork. Is this correct? https://github.com/Rahix/avr-hal/pull/18

**Comment by Rahix** [comment]
Yes, you did everything right!  Thank you very much!  Also, cheers for your first PR :tada:
