### ISSUE TITLE
Remove "singlethread": true

### ISSUE THREAD

**Issue by lights0123** [Rahix/avr-hal#21]
In all the target JSON files, `"singlethread": true` is set. However, I don't believe that this works—[interrupts can still cause problems](https://github.com/rust-lang/rust/issues/58500#issuecomment-654341233), as an interrupt happening at the wrong place can interfere with the operation. The only operation that AVR can perform safely is an 8-bit read or write. All other operations require disabling interrupts.

**Comment by Rahix** [comment]
Right, I wasn't aware of the true meaning of the field.  Thanks for pointing it out to me!

**Comment by lights0123** [comment]
For anyone coming across this in the future, I wrote a guide about what to do if you want to use the Atomic types: https://docs.rust-embedded.org/embedonomicon/custom-target.html#fill-the-target-file
