### ISSUE TITLE
"cargo generate --git ... " command not working 

### ISSUE THREAD

**Issue by exo-cortex** [Rahix/avr-hal#236]
The command "cargo generate --git https://github.com/Rahix/avr-hal-template.git" as described in the "starting your own project" section on the README page does not work for me (" error: no such command `generate` ").
I installed rustup with the curl script on fedora. 

edit: uh oh. I am kind of stupid. I didn't know that "cargo generate" was some functionality that has to be installed manually. 
(I wanted to start programming with my arduino, so I am still kind of unfamiliar with the whole rust ecosystem. Maybe some little hint for newbies like me could be added to the README page? Like " ( make sure the you installed the cargo-generate module )" maybe. 
I am sorry for that almost non-issue here. But I've been brooding over it during the last week. And now I fixed it upon revisiting it here.

**Comment by stappersg** [comment]
On Fri, Jan 21, 2022 at 01:18:04AM -0800, exocortex wrote:
> The command "cargo generate --git
> https://github.com/Rahix/avr-hal-template.git" as described in the
> "starting your own project" section on the README page does not work
> for me (" error: no such command `generate` ").
> I installed rustup with the curl script on fedora. 
> 

Please report back after visiting https://github.com/cargo-generate/cargo-generate

**Comment by exo-cortex** [comment]
I got it to work by using "cargo install cargo-generate"-command. I didn't know about sub-commands. Thank you very much!!!

**Comment by Rahix** [comment]
> Maybe some little hint for newbies like me could be added to the README page?

The README already says _"The best way to start your own project is via the [`avr-hal-template`](https://github.com/Rahix/avr-hal-template) which you can easily use with [`cargo-generate`](https://github.com/cargo-generate/cargo-generate)"_ ... Not sure if it might help to make it more explicit.  If you want, just send a PR rephrasing this part.

**Comment by stappersg** [comment]
On Sat, Jan 22, 2022 at 03:59:23AM -0800, Rahix wrote:
> If you want, just send a PR rephrasing this part.

#239


Regards
Stappers
