### ISSUE TITLE
Set up CI for avr-hal

### ISSUE THREAD

**Issue by Rahix** [Rahix/avr-hal#24]
Now that nightly can compile for AVR, it would make sense to set up CI here as well.

**Comment by lights0123** [comment]
One could theoretically host a custom GitHub Actions worker with an attached AVR device...

**Comment by Rahix** [comment]
> One could theoretically host a custom GitHub Actions worker with an attached AVR device...

I don't think that is worth it for our intents.  For now, I've set up build-testing; I think this will catch a large number of regressions already.  The next step would be creating test-binaries to run in _simavr_ which will hopefully catch logic regressions and miscompilations.
