### ISSUE TITLE
cannot find macro `llvm_asm` in this scope

### ISSUE THREAD

**Issue by piegamesde** [Rahix/avr-hal#254]
Apparently, `llvm_asm` was deprecated and removed over time, so it does not build anymore on current nightly.

**Comment by Rahix** [comment]
Yes, this is known, there is already a MR to update this: #229  As everyone is however still using the older nightly until upstream fixes land, we'll have to wait a bit longer before merging this...

**Comment by piegamesde** [comment]
Which nightly is the latest one that still works?

**Comment by stappersg** [comment]
> Which nightly is the latest one that still works?

You are all welcome at https://github.com/avr-rust/blink/issues/38
