### ISSUE TITLE
Compile avr-hal on windows 10?

### ISSUE THREAD

**Issue by MarkuBu** [Rahix/avr-hal#255]
What do I need to install on Windows 10 to be able to compile avr-hal?

Winavr? Current Arduino toolchain? PlatformIO? Is that even possible?

**Comment by Rahix** [comment]
I have no clue... Maybe check the other issues [labeled `windows`](https://github.com/Rahix/avr-hal/issues?q=is%3Aissue+sort%3Aupdated-desc+label%3Awindows+)?

**Comment by MarkuBu** [comment]
They are only related to ravedude.

**Comment by stappersg** [comment]
On Wed, Apr 06, 2022 at 01:21:08AM -0700, MarkuBu wrote:
> They are only related to ravedude.

Then start.

Yes, you will encounter obstacles.
Take http://www.catb.org/~esr/faqs/smart-questions.html as detour.

**Comment by Rahix** [comment]
@djdisodo, if you want you can add a short section to the README with details on installing all the dependencies needed on windows.

**Comment by djdisodo** [comment]
@Rahix https://github.com/Rahix/avr-hal/wiki/Setting-up-enviromment

**Comment by djdisodo** [comment]
@stappersg i fixed typo in the link right after

**Comment by stappersg** [comment]
> @stappersg i fixed typo in the link right after

Ah, _environment_ vs _enviromment_

What about
> add a short section to the README with details on installing all the dependencies needed on windows.

?

**Comment by Rahix** [comment]
I think we can just add a link to the wiki page in the README now, that'll be enough.

**Comment by Rahix** [comment]
I think with things like #349 hitting, it's time to close this issue.
