### ISSUE TITLE
Can only flash Nano with argument 'uno'

### ISSUE THREAD

**Issue by vcrn** [Rahix/avr-hal#336]
I'm having issues flashing Nano boards with `ravedude`. On a Uno, it works with having the runner in `.cargo/config.toml` as
```
runner = "ravedude Uno -cb 57600"
```
but with the Nano, it fails to find the port, so I have to specify this (this isn't an issue, but I'm adding the info in case it for some reason is useful). With the Nano, I'm using
```
runner = "ravedude nano -cb 57600 --port=/dev/ttyUSB0"
```
and it gives me the following message:

```
Programming target/avr-atmega328p/debug/testing-nano.elf => /dev/ttyUSB0
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x74
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x74
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x74
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0x74
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0x74
avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0x74
avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0x74
avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0x74
avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0x74
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0x74
avrdude: opening programmer "arduino" on port "/dev/ttyUSB0" failed
```
I'm able to flash it using the Arduino IDE. I've tried this on Manjaro Linux and Windows. I'm using `ravedude  v0.1.4` and `avrdude v7.0`. I'm using nightly-2022-07-10. The project is generated using the `avr-hal-template`. What I find strange is that I am able to flash it using the following `.cargo/config.toml`
```
[build]
target = "avr-specs/avr-atmega328p.json"

[target.'cfg(target_arch = "avr")']
runner = "ravedude uno -cb 57600 --port=/dev/ttyUSB0"

[unstable]
build-std = ["core"]
```
where I've simply changed `nano` to `uno` in the runner. 

Any idea what the issue might be?

**Comment by vcrn** [comment]
Looking at the code for `ravedude`, I can see that there's parts for handling the argument `nano-new` with the `display_name` "Arduino Nano (New Bootloader)". When I'm flashing the board using the Arduino IDE, I have Tools -> Processor set to "ATmega328P", not "ATmega328P (Old Bootloader)" which is available below. If I change to the old bootloader I get a similar error message:
```
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x74
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x5f
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x70
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0x75
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0x6d
avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0x70
avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0x5f
avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0x6f
avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0x6e
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0x3a
An error occurred while uploading the sketch
```
I've tried changing the argument from `nano` to `nano-new` for `ravedude`, but it just returns the error message: 'board not found'. I've also cloned the repository to make a new example using nano-new, to make sure what source code is used for `ravedude` but I still get the same error.

**Comment by Rahix** [comment]
Here you go: https://github.com/Rahix/avr-hal/releases/tag/ravedude-0.1.5 :)

**Comment by vcrn** [comment]
Thank you!
