### ISSUE TITLE
Cannot create expander for ...

### ISSUE THREAD

**Issue by unavoidable0100** [Rahix/avr-hal#402]
Hi there,

I set up a project with cargo generate for Arduino Uno, although it's running perfectly, rust-analyzer gives me an error

```
proc macro `entry` not expanded: Cannot create expander for /home/path/to/project/target/debug/deps/libavr_device_macros-8c55ff3523662538.so: unsupported ABI `rustc 1.64.0-nightly (6dba4ed21 2022-07-09)`rust-analyzer[unresolved-proc-macro](https://rust-analyzer.github.io/manual.html#unresolved-proc-macro)
```
![image](https://user-images.githubusercontent.com/77761282/224020883-b8d13eb1-81a7-4d58-9047-fb150773ebb1.png)

I've been searching for possible fixes but I couldn't find anything here in issues.

Any hint would be much appreciated, cheers !

**Comment by unavoidable0100** [comment]
I've found a "solution"
I basically disabled the errors for `unresolved-proc-macro`  in rust-analyzer settings but is this the correct way to resolve this?

```
    "rust-analyzer.diagnostics.disabled": [
        "unresolved-proc-macro"
    ],
```

**Comment by Rahix** [comment]
Hi,

I think you need to post this issue on the rust-analyzer bug tracker.  I don't think this is something strictly related to avr-hal.

**Comment by unavoidable0100** [comment]
hey, ok ! I'll search for advice there, thank you, closing the issue

**Comment by BoManev** [comment]
Here's an [article](https://fasterthanli.me/articles/proc-macro-support-in-rust-analyzer-for-nightly-rustc-versions) explaining the root cause of this issue. This was fixed for versions starting 2022-08-*.
Im nor sure how this could be fixed. @Rahix can the rustc version be bumped

**Comment by Rahix** [comment]
rustc version bump is currently blocked on https://github.com/rust-lang/rust/pull/106619 unfortunately...

**Comment by BoManev** [comment]
I found a solution. VS Code starts 2 processes one for rust-analyzer and one for the proc_macro server. It searches for the proc_macro executable in the `nightly-xxx/libexec`. Install `nightly-2022-08-03-x86_64-unknown-linux-gnu` (the earliest version to include the executable) and then copy the `libexec/rust-analyzer-proc-macro-srv` from the 08-03 nightly to the 07-10. 

@Rahix maybe we should add this fix to the repo readme (assuming that a lot of ppl use VSCode)
