### ISSUE TITLE
Mutex::borrow: Should it return a &mut T?

### ISSUE THREAD

**Issue by aleokdev** [Rahix/avr-hal#414]
I'm wondering, shouldn't [`Mutex::borrow`](https://rahix.github.io/avr-hal/avr_device/interrupt/struct.Mutex.html#method.borrow) already return a mutable reference, as there is no danger from other cores touching that data at the same time? [std::Mutex::lock](https://doc.rust-lang.org/std/sync/struct.Mutex.html#method.lock) does allow retrieving a mutable reference for that same reason.

**Comment by aleokdev** [comment]
Thinking about it better calling borrow twice would create an invalid mutable reference. Hmm

**Comment by Rahix** [comment]
For documentation: If you need mutable references, you need to put a `RefCell` inside of the `Mutex`.
