### ISSUE TITLE
Support Arduino Pro Mini (5V 16Mhz/3.3V 8Mhz)

### ISSUE THREAD

**Issue by tippfehlr** [Rahix/avr-hal#425]
This should be fairly straight forward because the Pro Mini 5V is exactly the same as the Arduino Nano, but without the onboard USB.

I use an Arduino Pro Mini 3.3V, and while flashing it with the Arduino Nano target (feature) works, I have to double all timers (eg. baud rate, millis) because the mcu runs at half clock speed.

**Comment by norepimorphism** [comment]
(Not sure if GitHub already sends notifications for mentions, but I have created a PR at #435 for Pro Mini 5V support.)

**Comment by tippfehlr** [comment]
Thanks @norepimorphism!
