### ISSUE TITLE
peripherals type alias

### ISSUE THREAD

**Issue by djdisodo** [Rahix/avr-hal#555]
i think peripherals type names are hard to write and remember currently,

it makes some problem because rust requires you to put type on generic parameters, function arguments or static/const values

for example how can tell what's type of pin d9 on UNO is? `atmega_hal::port::PB1`

however names should be different depending on the board

first, maybe we can introduce some macro that parses given value and return the type

iirc this is used in syn with `token!` macro

or we can just create type alias

**Comment by Rahix** [comment]
> for example how can tell what's type of pin d9 on UNO is? atmega_hal::port::PB1

This is a good point.  I think the `avr_hal_generic::renamed_pins! {}` macro should generate type aliases for the pins at least.  This also shouldn't be too difficult to achieve.

**Comment by Rahix** [comment]
(Created #558 to track this)
