### ISSUE TITLE
Runtime?

### ISSUE THREAD

**Issue by jonahbron** [Rahix/avr-hal#6]
All of the chip implementations in the official Rust Embedded project are split into two packages: low level registry access and run-time.

Does that (or will it) map onto the two packages here (avr-device and avr-hal)?  Does (or will) avr-hal provide a run-time?

**Comment by Rahix** [comment]
There is very little runtime code necessary for AVR, so I intend to have all of it in `avr-device`.

**Comment by jonahbron** [comment]
> I intend to

That implies it's not done yet, yet the README has instructions on how to build a hex file ready to flash onto a board.  I totally don't understand how this stuff works, but it seems like a program can't work yet without a runtime?  Or am I missing something?

**Comment by Rahix** [comment]
The bare minimum is there already, it is just not pretty yet.  For example, the main function has to be a

```rust
#[no_mangle]
pub extern fn main() -> ! {
    // ...
}
```

right now, in contrast to

```rust
#[entry]
fn main() -> ! {
    // ...
}
```

**Comment by jonahbron** [comment]
@Rahix Ahhh I see.  Where in the code can I look to see how that works?   I've dug around but found nothing seems related to that.

**Comment by Rahix** [comment]
The current "runtime" is generated by `avr-gcc`, so there is not much in any of my crates right now.  In the future, there should be a procedural macro `entry` as shown above that takes care of doing all that setup.  I am not yet sure how exactly that should look.

**Comment by jonahbron** [comment]
Got it.  Thanks very much for explaining that.
