### ISSUE TITLE
cargo run - Error: Failed reading avrdude version information. 

### ISSUE THREAD

**Issue by alter-kaker** [Rahix/avr-hal#600]
Trying to set up a Rust toolchain for Arduino because I'm no good at all with C/C++.

I'm using the `cargo generate --git https://github.com/Rahix/avr-hal-template.git` template. Build goes fine, but cargo-run gives the following output:
```
$ cargo run
    Finished `dev` profile [optimized + debuginfo] target(s) in 0.17s
     Running `ravedude nano -cb 57600 target/avr-atmega328p/debug/mediaplayer.elf`
Error: Failed reading avrdude version information.

Caused by: No such file or directory (os error 2)
```

I'm running Arch (EndeavorOS), fully updated as of today.

Thanks!

**Comment by alter-kaker** [comment]
I needed to install avrdude.

**Comment by Rahix** [comment]
I guess we could add a check that avrdude is even there before trying to read out the version.  The error message would then be a lot less confusing!
